phrase:
  access_token: 97aff8cd5c10897365e6198ae46b44871c024a26c51b8a3e75393b6eea4a5cc3
  project_id: dc4b764752d18bc8a48e898432a343c5
  file_format: "simple_json"
  push:
    sources:
      - file: src\assets\translation\en-GB.json
        params:
          locale_id: "en-GB",
          file_format: simple_json
  pull:
    targets:
      - file: src\assets\translation\<locale_name>.json
        params:
          file_format: simple_json
      - file: backend\<locale_name>.json
        params:
          file_format: resx
      - file: ios\<locale_name>.json
        params:
          file_format: strings
